### ISSUE TITLE
`signTransaction` Doesn't Always Handle Smart Contract Errors Correctly

### ISSUE THREAD

**Issue by kylanhurt** [telosnetwork/app-telos-native#162] opened 2022-09-30 12:54 UTC
**Describe the bug**

When a smart contract throws an error, the handling of the error appears to make false assumptions about the structure of the error object. Notice, specifically the `json` property, which is not read in the current code base. This results in an 

![image](https://user-images.githubusercontent.com/6249205/193273865-e522296f-e669-494c-8ec6-1c95bb12d253.png)

![image](https://user-images.githubusercontent.com/6249205/193274027-bc9e4113-f6c8-456b-a4d2-466bac8a17a5.png)

**Comment by karynemayer** [comment] 2022-09-30 15:37
@kylanhurt I'm wondering if this would not be a duplicate of #130 , but describe the root cause of the problem.

**Comment by kylanhurt** [comment] 2022-10-01 20:12
@karynemayer Yes you could argue that this could possibly be considered a duplicate. I will take my comments over to that issue.

**Closed** 2022-10-04 18:21 UTC
Labels: duplicate
